# Schema for the configuration files of the Hello World module.

# Documentation for schema files like this one is located here:
# https://drupal.org/node/1905070

hello.settings:
  #type: mapping
  type: config_object
  label: 'Hello config'
  mapping:
    hello_value:
      type: string
      label: 'Hello Value'

